partial state

diff --git a/testdir/REGRESS b/testdir/REGRESS
--- a/testdir/REGRESS
+++ b/testdir/REGRESS
@@ -19,4 +19,7 @@ oldawk=$oldawk awk=$awk Compare.T1
 
 oldawk=$oldawk awk=$awk Compare.tt tt.*
 	echo `ls tt.* | wc -l` tests; echo
+
+oldawk=$oldawk awk=$awk Compare.t test_jit_memory.awk
+if [ $? -ne 0 ]; then echo "test_jit_memory.awk: FAILED"; fi
 oldawk= awk= Compare.t t.jit_simd.awk
